env:
  TERM: xterm-256color
window:
  dynamic_padding: true
  opacity: 0.92
  startup_mode: Maximized
  title: Alacritty
  dynamic_title: true
scrolling:
  history: 20000
font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  bold_italic:
    family: monospace
    style: Bold Italic
colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'
  hints:
    start:
      foreground: CellBackground
      background: '#88c0d0'
    end:
      foreground: '#d8dee9'
      background: '#434c5e'
  transparent_background_colors: true
live_config_reload: true
shell:
  program: /usr/bin/env
  args:
    - zsh
    - -l
    - -c
    - "tmux attach || tmux"
key_bindings:
  # Apply xterm-like "modifyOtherKeys" sequences to C-(number).
  #
  # See codes at https://invisible-island.net/xterm/modified-keys-gb-pc105.html
  # and convert something like `\E[27;5;54~` to `\x1b[54;5u`.
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Key1, mods: Control, chars: "\x1b[49;5u" }
  - { key: Key2, mods: Control, chars: "\x1b[50;5u" }
  - { key: Key3, mods: Control, chars: "\x1b[51;5u" }
  - { key: Key4, mods: Control, chars: "\x1b[52;5u" }
  - { key: Key5, mods: Control, chars: "\x1b[53;5u" }
  - { key: Key6, mods: Control, chars: "\x1b[54;5u" }
  - { key: Key7, mods: Control, chars: "\x1b[55;5u" }
  - { key: Key8, mods: Control, chars: "\x1b[56;5u" }
  - { key: Key9, mods: Control, chars: "\x1b[57;5u" }
