#!/usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set the wallpaper.
feh --bg-fill $MY_NIXOS_WALLS/mountain.jpg &

xrandr --output DisplayPort-0 --auto --primary --output HDMI-0 --auto --left-of DisplayPort-0

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width  2
bspc config window_gap    8
# TODO: enable after polybar is added -> bspc config top_padding  32

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true
